version: 2
jobs:
    build:
      docker:
      steps:
       - checkout
       - run:
            name: awscli
            command: sudo pip install awscli
    deploy:  |
       if [ "${CIRCLE_BRANCH}" == "master" ]; then
         aws s3 sync home\ubuntu\whaleteeth_website s3://www.whaleteethmusic.com --delete
       fi
workflows:
  version: 2
  build-and-deploy:
    jobs:
     - build
     - deploy
